// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6QjZ34u5WBqNstTGpx9i-YRlgM8huJ7o',
    appId: '1:458064958537:web:aed2bb7546316d75ae9b98',
    messagingSenderId: '458064958537',
    projectId: 'itike-9c56e',
    authDomain: 'itike-9c56e.firebaseapp.com',
    storageBucket: 'itike-9c56e.appspot.com',
    measurementId: 'G-MPEZG4DBCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-CZZNnkSlwIbSPv-I8dGLuyNEPGQLkc',
    appId: '1:458064958537:android:dcd3e46ec8287fe0ae9b98',
    messagingSenderId: '458064958537',
    projectId: 'itike-9c56e',
    storageBucket: 'itike-9c56e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWM3ChvM621-zG3wlT9o9ArD59xoYNC-Y',
    appId: '1:458064958537:ios:648a66f713502752ae9b98',
    messagingSenderId: '458064958537',
    projectId: 'itike-9c56e',
    storageBucket: 'itike-9c56e.appspot.com',
    androidClientId: '458064958537-9rna9bo1l9dhpjuvvfe0gk3d490f6p1i.apps.googleusercontent.com',
    iosClientId: '458064958537-146r42nbcrhqrliv8jvtdr1itfrj8sr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWM3ChvM621-zG3wlT9o9ArD59xoYNC-Y',
    appId: '1:458064958537:ios:648a66f713502752ae9b98',
    messagingSenderId: '458064958537',
    projectId: 'itike-9c56e',
    storageBucket: 'itike-9c56e.appspot.com',
    androidClientId: '458064958537-9rna9bo1l9dhpjuvvfe0gk3d490f6p1i.apps.googleusercontent.com',
    iosClientId: '458064958537-146r42nbcrhqrliv8jvtdr1itfrj8sr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTicket',
  );
}
